### ISSUE TITLE
Interface messed up (FL Studio, Win10)

### ISSUE THREAD

**Issue by egnrse** [mtytel/helm#256]
![Helm_Err_Interface](https://user-images.githubusercontent.com/30458827/85419545-84f88480-b572-11ea-812b-4c717fc93027.png)
I downloaded Helm recently, I am using Win10.
As standalone Helm works fine. But I can't get it to function properly in my DAW (FL Studio version 20.7). When importet the Interface of Helm is completly messed up look at the screenshot.
It is still making sounds when midi input is given.
Messing with the DAW settings for vst Plugins didn't helped so far.

**Comment by mtytel** [comment]
This is already fixed in code I just haven't created a new installer.

**Comment by ezxpro** [comment]
@mtytel the very exact same bug persists in version 0.9.0 when using the latest FL studio build. Only way to fix it is to set FL Studio's scaling to a 100%, which makes everything unreadable at 4k and above.

**Comment by chromosthete** [comment]
I am having the same issue, I have the most recent version of the plugin

**Comment by silverv** [comment]
Same issue

**Comment by thistleknot** [comment]
same issue with both 32 and 64
https://www.reddit.com/r/FL_Studio/comments/1aodutc/helm_vst_plugin_some_visual_bug/

**Comment by SylHamelink** [comment]
I just downloaded the helm plugin and I also have the same problem, I have tried every solution given online and nothing helps.
